services:
  app:
    image: maven:3.9.9-eclipse-temurin-21
    environment:
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s
