server.port=8080
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
logging.level.org.springframework.amqp=INFO
logging.level.br.edu.eventdriven=INFO
logging.file.name=logs/event-driven.log
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
